name: Auto Update
on:
  schedule:
    - cron:  "0 5 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Run a one-line script
      run: bash ./release.sh
      
    - name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
           commit_message: Auto Update
           branch: main
           commit_options: '--no-verify --signoff'
           repository: .
           commit_user_name: My GitHub Actions Bot
           commit_user_email: my-github-actions-bot@example.org
           commit_author: Author <actions@github.com>
           push_options: '--force'
